# Generated by Django 3.1.7 on 2021-03-07 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RecordType",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name="BalanceSheet",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("balance", models.FloatField(default=0)),
                (
                    "record_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tracker.recordtype"),
                ),
            ],
        ),
    ]
