# Generated by Django 3.1.7 on 2021-03-07 03:15

from django.db import migrations


def seed_record_types(apps, schema_editor):
    record_type = apps.get_model("tracker", "RecordType")
    for type_ in ["Asset", "Liability"]:
        asset = record_type(name=type_)
        asset.save()


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_auto_20210307_0248"),
    ]

    operations = [migrations.RunPython(seed_record_types)]
